### ISSUE TITLE
Sf 3.4/4.0 compatibility

### ISSUE THREAD

**Issue by acrobat** [bernardphp/BernardBundle#59]
- [x] Check the bundle against symfony 3.4 and fix the deprecations
- [x] Make sure the bundle can be installed/used with sf 4

**Comment by acrobat** [comment]
I think we reached full compatibility with sf3.4 and sf4. I've installed the bundles with a clean symfony 4 (with flex) install and everything worked as expected after all the fixes.

**Comment by acrobat** [comment]
Reopening the issue as I found some problems with the debug command

**Comment by Bukashk0zzz** [comment]
Hi,

get this error:
 Problem 1
    - Conclusion: don't install symfony/symfony v4.0.1
    - bernard/bernard 1.0.0-alpha2 requires symfony/event-dispatcher ~2.3 || ~3.0 -> satisfiable

**Comment by Bukashk0zzz** [comment]
So problem that bernard/bernard use old symfony/event-dispatcher can you please update this?

**Comment by acrobat** [comment]
Hmm yes, I've used a symfony flex setup to test this but it used indeed the 3.4 version of the event-dispatcher. Therefor I didn't have any issues. 

I will bump the version on the library itself and post and update in this issue! Thanks for reporting!

**Comment by stephpy** [comment]
Thanks for this work :) 🍻 

When do you plan to create a release with theses changes ?

**Comment by acrobat** [comment]
I'm currently waiting for bernardphp/normalt#9 to be merged and have a new version of normat released. When this is done I can fix sf4 support on bernard and tag a new version of this bundle.

I hope to do it before the end of the year, but it depends on when the normalt pr gets merged

**Comment by tomaskadlec** [comment]
Any update on this issue? I am looking forward to have BernardBundle in SF4. Thanks for all the work!

**Comment by acrobat** [comment]
I just tagged a new version of `bernard/normalt` and `bernard/bernard`. I'm going to test this in a sf4 setup and tag a new version of the bundle, hopefully, in the next few days!

**Comment by acrobat** [comment]
@tomaskadlec feel free to test also in you application if the current `dev-master` of the bundle works on sf4. Thanks!

**Comment by mipapo** [comment]
updates?

**Comment by mikemix** [comment]
It would be nice if you could finally tag this.

**Comment by acrobat** [comment]
I'm currently busy on other projects so I don't really have time to actively test the sf4 compatibility. So it would be a huge help if you could test `dev-master` and report any issues you find. 
I think sf4 support is 90% done but maybe some small things are still left. If the master branch is tested by a few people we are good to go to tag a release!

**Comment by mipapo** [comment]
What I can say: I'm using Symfony 3.4.4 with current dev-master  (which uses bernard/bernard 1.0.0-alpha9). Using Amazon SQS as Messagequeue. (I just need to find time to update the doc of Amazon SQS  in this repo. (I use the latest amazon sdk php - in bernard/bernard a very old version 2.4 of aws-sdk-php is provided)

Using aws-sdk-php 2.4->2.8
```
  sqs_client:
      class: Aws\Sqs\SqsClient
      factory: ['Aws\Sqs\SqsClient', factory]
      arguments:
          -
              credentials: { key: "%amazon.sqs.key%", secret: "%amazon.sqs.secret%" }
              region: "%amazon.sqs.region%"
```
Using aws-sdk-php 3.60...
```
  sqs_client:
      class: Aws\Sqs\SqsClient
      factory: ['Aws\Sqs\SqsClient', factory]
      arguments:
          -
              credentials: { key: "%amazon.sqs.key%", secret: "%amazon.sqs.secret%" }
              region: "%amazon.sqs.region%"
              version: "2012-11-05" 
```
