### ISSUE TITLE
Allow to specify method on receiver service tag

### ISSUE THREAD

**Issue by diimpp** [bernardphp/BernardBundle#77]
Hi,

would be cool to be able to specify which method should handle message processing.

Like so
```
my_receiver:
    class: Acme\Receiver
    # public: true # Make sure the service is public
    tags:
         - { name: bernard.receiver, message: SendNewsletter, method: sendMyNewsletter }
         - { name: bernard.receiver, message: ImportUsers }
```
