### ISSUE TITLE
How to reach Object on Consumer? 

### ISSUE THREAD

**Issue by bencagri** [bernardphp/BernardBundle#82]
Hi, im able to produce messages with this configuration;

bernard.yaml
```yml 
bernard:
    driver: file # you can choose predis, phpredis, file, doctrine, sqs etc.
```
services.yaml
```yml
  my.producer:
      class: App\Queue\MailProducer
      arguments: [
          '@bernard.producer',
          '@jms_serializer'
          ]
```
MailProducer.php
```php

use App\Entity\Mail;
use Bernard\Message\PlainMessage;
use Bernard\Producer;
use JMS\Serializer\Serializer;
use JMS\Serializer\SerializerInterface;

class MailProducer
{

    /**
     * @var Producer
     */
    protected $producer;
    /**
     * @var Serializer
     */
    private $serializer;

    public function __construct
    (
        Producer $producer,
        SerializerInterface $serializer
    )
    {
        $this->producer = $producer;
        $this->serializer = $serializer;
    }

    public function produce(Mail $mail)
    {

        $serializedData = $this->serializer->serialize($mail, 'json');

        $message = new PlainMessage('mail', ['mail' => $serializedData]);
        $this->producer->produce($message);
    }
}
```

when I call produce method in MailProducer service, I see the files, Berbard produces messages. Its perfect.
But then, how may I reach my Mail object on consumer?
